// Root entry: the core sync mapper plus the serialize codec.
export const VERSION = "0.1.0";

export {
  createMap,
  OneWayRuleError,
  ReverseKeyCollisionError,
  MapHasNoResolversError,
  fromResolver,
  getPath,
  setPath,
  isStringRule,
  isFnRule,
  isPairRule,
  isFromResolverRule,
  isDefaultRule,
  withDefault,
  toSnakeCase,
  toCamelCase,
  toKebabCase,
  toPascalCase,
  toConstantCase,
  toSnakeKey,
  toCamelKey,
  toKebabKey,
  toPascalKey,
  toConstantKey,
  splitWords,
  type SnakeCased,
  type CamelCased,
  forwardMany,
  reverseMany,
  safeForward,
  pick,
  omit,
  compose,
  type TypeMapper,
  type RuleMap,
  type Rule,
  type FnRule,
  type PairRule,
  type FromResolver,
  type DefaultRule,
  type SafeResult,
} from "./map/index.js";

export {
  serialize,
  deserialize,
  deserializeAsync,
  CodecError,
  AsyncSchemaError,
} from "./serialize/index.js";
